/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ClubVaultInterface extends Interface {
    getFunction(nameOrSignature: "approveProposal" | "cancelProposal" | "createProposal" | "createVault" | "deposit" | "executeProposal" | "getProposal" | "getVault" | "getVaultMembers" | "getVaultProposalIds" | "hasApprovedProposal" | "isVaultMember" | "proposalCount" | "vaultCount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "ProposalApproved" | "ProposalCancelled" | "ProposalCreated" | "ProposalExecuted" | "VaultCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'approveProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProposal', values: [BigNumberish, AddressLike, BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'createVault', values: [string, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVaultMembers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVaultProposalIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasApprovedProposal', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isVaultMember', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'vaultCount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approveProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVaultMembers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVaultProposalIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasApprovedProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isVaultMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaultCount', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [vaultId: BigNumberish, from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [vaultId: bigint, from: string, amount: bigint];
      export interface OutputObject {vaultId: bigint, from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalApprovedEvent {
      export type InputTuple = [proposalId: BigNumberish, vaultId: BigNumberish, approver: AddressLike, approvalCount: BigNumberish];
      export type OutputTuple = [proposalId: bigint, vaultId: bigint, approver: string, approvalCount: bigint];
      export interface OutputObject {proposalId: bigint, vaultId: bigint, approver: string, approvalCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCancelledEvent {
      export type InputTuple = [proposalId: BigNumberish, vaultId: BigNumberish, cancelledBy: AddressLike];
      export type OutputTuple = [proposalId: bigint, vaultId: bigint, cancelledBy: string];
      export interface OutputObject {proposalId: bigint, vaultId: bigint, cancelledBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, vaultId: BigNumberish, proposer: AddressLike, recipient: AddressLike, amount: BigNumberish, title: string];
      export type OutputTuple = [proposalId: bigint, vaultId: bigint, proposer: string, recipient: string, amount: bigint, title: string];
      export interface OutputObject {proposalId: bigint, vaultId: bigint, proposer: string, recipient: string, amount: bigint, title: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecutedEvent {
      export type InputTuple = [proposalId: BigNumberish, vaultId: BigNumberish, executor: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [proposalId: bigint, vaultId: bigint, executor: string, recipient: string, amount: bigint];
      export interface OutputObject {proposalId: bigint, vaultId: bigint, executor: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultCreatedEvent {
      export type InputTuple = [vaultId: BigNumberish, name: string, approvalThreshold: BigNumberish, members: AddressLike[]];
      export type OutputTuple = [vaultId: bigint, name: string, approvalThreshold: bigint, members: string[]];
      export interface OutputObject {vaultId: bigint, name: string, approvalThreshold: bigint, members: string[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ClubVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): ClubVault;
    waitForDeployment(): Promise<this>;

    interface: ClubVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createProposal: TypedContractMethod<
      [vaultId: BigNumberish, recipient: AddressLike, amount: BigNumberish, title: string, description: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    createVault: TypedContractMethod<
      [name: string, members: AddressLike[], ],
      [bigint],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    executeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, bigint] & {vaultId: bigint, proposer: string, recipient: string, amount: bigint, title: string, description: string, approvalCount: bigint, status: bigint, createdAt: bigint, executedAt: bigint }],
      'view'
    >
    

    
    getVault: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {name: string, approvalThreshold: bigint, memberCount: bigint, balance: bigint }],
      'view'
    >
    

    
    getVaultMembers: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getVaultProposalIds: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    hasApprovedProposal: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isVaultMember: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    proposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vaultCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProposal'): TypedContractMethod<
      [vaultId: BigNumberish, recipient: AddressLike, amount: BigNumberish, title: string, description: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createVault'): TypedContractMethod<
      [name: string, members: AddressLike[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'executeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, bigint] & {vaultId: bigint, proposer: string, recipient: string, amount: bigint, title: string, description: string, approvalCount: bigint, status: bigint, createdAt: bigint, executedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getVault'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {name: string, approvalThreshold: bigint, memberCount: bigint, balance: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getVaultMembers'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getVaultProposalIds'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasApprovedProposal'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isVaultMember'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vaultCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'ProposalApproved'): TypedContractEvent<ProposalApprovedEvent.InputTuple, ProposalApprovedEvent.OutputTuple, ProposalApprovedEvent.OutputObject>;
getEvent(key: 'ProposalCancelled'): TypedContractEvent<ProposalCancelledEvent.InputTuple, ProposalCancelledEvent.OutputTuple, ProposalCancelledEvent.OutputObject>;
getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalExecuted'): TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
getEvent(key: 'VaultCreated'): TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;

    filters: {
      
      'Deposited(uint256,address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'ProposalApproved(uint256,uint256,address,uint64)': TypedContractEvent<ProposalApprovedEvent.InputTuple, ProposalApprovedEvent.OutputTuple, ProposalApprovedEvent.OutputObject>;
      ProposalApproved: TypedContractEvent<ProposalApprovedEvent.InputTuple, ProposalApprovedEvent.OutputTuple, ProposalApprovedEvent.OutputObject>;
    

      'ProposalCancelled(uint256,uint256,address)': TypedContractEvent<ProposalCancelledEvent.InputTuple, ProposalCancelledEvent.OutputTuple, ProposalCancelledEvent.OutputObject>;
      ProposalCancelled: TypedContractEvent<ProposalCancelledEvent.InputTuple, ProposalCancelledEvent.OutputTuple, ProposalCancelledEvent.OutputObject>;
    

      'ProposalCreated(uint256,uint256,address,address,uint256,string)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalExecuted(uint256,uint256,address,address,uint256)': TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
      ProposalExecuted: TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
    

      'VaultCreated(uint256,string,uint64,address[])': TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
      VaultCreated: TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
    
    };
  }